### ISSUE TITLE
Gitbook link not working anymore

### ISSUE THREAD

**Issue by xenide** [markomanninen/creativepowerofthefloweroflife#1]
I've seen your first book. I think it's really awesome work, I hope you're still researching deeper into this.

The link on the sidebar doesn't seem to be working anymore. Perhaps you want to update it?

**Comment by markomanninen** [comment]
Thanks, I updated link to my subdomain adress that gives the online book: https://creative.flowerofliferesearch.com/

I haven't been working with the subject for few years now, just made an essay in Finnish language a year ago that loosely relates to it. But glad to hear it has been read and perhaps gives ideas and material for further study.
